version: '3.8'
services:
  db-user:
    container_name: db-user-service
    image: postgres:16
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB}
      POSTGRES_USER: ${USER_SERVICE_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - ./volumes/user-service:/data/postgres
    env_file:
      - ./.env

  db-task:
    container_name: db-task-service
    image: postgres:16
    environment:
      POSTGRES_DB: ${TASK_SERVICE_DB}
      POSTGRES_USER: ${TASK_SERVICE_USER}
      POSTGRES_PASSWORD: ${TASK_SERVICE_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - ./volumes/task-service:/data/postgres
    env_file:
      - ./.env

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.101.0
    ports:
      - '8428:8428'
    volumes:
      - ./config/victoria-metrics/promscrape.yml:/etc/victoria-metrics/promscrape.yml
    command: '-promscrape.config=/etc/victoria-metrics/promscrape.yml'

  grafana:
    container_name: grafana
    image: grafana/grafana:11.1.0
    ports:
      - '3000:3000'
    links:
      - victoria-metrics:victoria-metrics
    volumes:
      - ./data/grafana:/var/lib/grafana
    env_file:
      - ./.env
    environment:
      - GF_SECURITY_ADMIN_USER=${GF_SECURITY_ADMIN_USER}
      - GF_SECURITY_ADMIN_PASSWORD=${GF_SECURITY_ADMIN_PASSWORD}

  grafana-loki:
    container_name: grafana-loki
    image: grafana/loki:3.0.0
    ports:
      - '3100:3100'


networks:
  task-manager:
    driver: bridge