name: 'task-manager'

services:
  db-user:
    container_name: db-user-service
    image: postgres:16
    environment:
      POSTGRES_DB: ${USER_SERVICE_DB}
      POSTGRES_USER: ${USER_SERVICE_USER}
      POSTGRES_PASSWORD: ${USER_SERVICE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", $$POSTGRES_USER, "-d", $$POSTGRES_DB ]
    ports:
      - '5433:5432'
    volumes:
      - db-user-service-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  db-task:
    container_name: db-task-service
    image: postgres:16
    environment:
      POSTGRES_DB: ${TASK_SERVICE_DB}
      POSTGRES_USER: ${TASK_SERVICE_USER}
      POSTGRES_PASSWORD: ${TASK_SERVICE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready", "-U", $$POSTGRES_USER, "-d", $$POSTGRES_DB ]
    ports:
      - '5434:5432'
    volumes:
      - db-task-service-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  db-productivity:
    container_name: db-productivity-service
    image: mongo:8
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${PRODUCTIVITY_SERVICE_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${PRODUCTIVITY_SERVICE_PASSWORD}
    healthcheck:
      test: [ "CMD-SHELL", "mongosh", "--eval", "db.adminCommand('ping')" ]
    ports:
      - '27017:27017'
    volumes:
      - db-productivity-service-data:/var/lib/postgresql/data
    env_file:
      - ./.env

  zookeeper:
    container_name: zookeeper
    image: confluentinc/cp-zookeeper:7.6.1
    ports:
      - '2181:2181'
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    container_name: kafka
    image: confluentinc/cp-kafka:7.6.1
    depends_on:
      - zookeeper
    ports:
      - '9092:9092'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1

  keycloak:
    container_name: keycloak
    image: quay.io/keycloak/keycloak:25.0.2
    command: start-dev --import-realm --config-file=/opt/keycloak/conf/keycloak-server.json
    ports:
      - '18080:8080'
    volumes:
      - keycloak-config:/opt/keycloak
      - ./auth-service/target/auth-service-0.0.1-SNAPSHOT.jar:/opt/keycloak/providers/keycloak-event-listener.jar
    env_file:
      - ./.env

  victoria-metrics:
    container_name: victoria-metrics
    image: victoriametrics/victoria-metrics:v1.101.0
    command: -promscrape.config=/etc/victoria-metrics/promscrape.yml
    ports:
      - '8428:8428'
    volumes:
      - victoria-metrics-config:/etc/victoria-metrics

  grafana:
    container_name: grafana
    image: grafana/grafana:11.1.0
    ports:
      - '3000:3000'
    volumes:
      - grafana-data:/var/lib/grafana
    env_file:
      - ./.env

  grafana-loki:
    container_name: grafana-loki
    image: grafana/loki:3.0.0
    ports:
      - '3100:3100'

  grafana-tempo-tracing:
    container_name: grafana-tempo
    image: grafana/tempo:2.5.0
    command: -config.file=/etc/grafana-tempo/tempo.yml
    ports:
      - '3200:3200'
      - '9411:9411' # zipkin
    volumes:
      - grafana-tempo-config:/etc/grafana-tempo

networks:
  task-manager:
    driver: bridge

volumes:
  db-user-service-data:
  db-task-service-data:
  db-productivity-service-data:
  grafana-data:
  keycloak-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/keycloak

  victoria-metrics-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/victoria-metrics

  grafana-tempo-config:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: ./config/tempo
