server:
  port: 8080
spring:
  application:
    name: api-gateway
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@localhost:8888