scrape_configs:
  - job_name: 'user-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8081" ]
        labels:
          application: 'user-service'
          instance: 'host.docker.internal:8081'
  - job_name: 'task-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ "host.docker.internal:8082" ]
        labels:
          application: 'task-service'
          instance: 'host.docker.internal:8082'