server:
  port: 8084
spring:
  application:
    name: productivity-service
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@localhost:8888