server:
  port: 8080
  forward-headers-strategy: framework
spring:
  main:
    web-application-type: reactive
  cloud:
    gateway:
      routes:
        - id: eureka-service-route
          uri: http://${EUREKA_SERVER_HOST:localhost:8761}
          predicates:
            - Host=/eureka/web
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Host=/api/v1/users/**
        - id: task-service-route
          uri: lb://task-service
          predicates:
            - Host=/api/v1/tasks/**
        - id: productivity-service-route
          uri: lb://productivity-service
          predicates:
            - Host=/api/v1/productivity/**
auth-service:
  uri: http://host.docker.internal:8084
logging:
  level:
    root: INFO
    org.springframework.cloud.gateway.route.RouteDefinitionRouteLocator: INFO
    org.springframework.cloud.gateway: TRACE
    org.springframework.security: DEBUG
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost:8761}/eureka/
    registryFetchIntervalSeconds: 1
management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus