server:
  port: 8084
spring:
  kafka:
    bootstrap-servers: localhost:9092
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://host.docker.internal:18080/realms/task-manager
keycloak:
  server-url: http://host.docker.internal:18080
  realm: task-manager
  client-id: ${KEYCLOAK_CLIENT_ID}
  client-secret: ${KEYCLOAK_CLIENT_SECRET}
logging:
  level:
    root: INFO
    org.springframework.security: TRACE
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost:8761}/eureka/
    registryFetchIntervalSeconds: 1
management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus