server:
  port: 8083
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://host.docker.internal:8761/eureka/
    registryFetchIntervalSeconds: 1
management:
  zipkin:
    tracing:
      endpoint: http://host.docker.internal:9411/api/v2/spans
  tracing:
    sampling:
      probability: 1.0