server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://${USER_SERVICE_DB_HOST:localhost:5433}/${USER_SERVICE_DB}
    username: ${USER_SERVICE_USER}
    password: ${USER_SERVICE_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
logging:
  level:
    root: info
eureka:
  instance:
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 1
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://${EUREKA_SERVER_HOST:localhost:8761}/eureka/
    registryFetchIntervalSeconds: 1
management:
  zipkin:
    tracing:
      endpoint: http://${ZIPKIN_HOST:localhost:9411}/api/v2/spans
  tracing:
    sampling:
      probability: 1.0
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus