server:
  port: 8081
spring:
  application:
    name: user-service
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@localhost:8888