server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/user-service
    username:
    password:
    driver-class-name: org.postgresql.Driver
  jpa:
    properties.hibernate:
      show_sql: true
      format_sql: true
      hbm2ddl.auto: validate
    open-in-view: false
logging:
  level:
    root: info
management:
  endpoints:
    web:
      exposure:
        include:
          - health
          - prometheus