server:
  port: 8083
spring:
  application:
    name: storage-service
  config:
    import: 'configserver:'
  cloud:
    config:
      uri: http://${CONFIG_SERVER_USER}:${CONFIG_SERVER_PASSWORD}@localhost:8888