name: 'Publish Validation Starter'

on:
  push:
    branches: [ 'master' ]
    paths: [ 'validation-starter/**' ]
  workflow_dispatch:
env:
  STARTER: validation-starter
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
jobs:
  publish:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.1.7

      - name: Set up JDK 21
        uses: actions/setup-java@v4.2.2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Build starter
        run: mvn clean install -f ${{ env.STARTER }}

      - name: Publish starter to GitHub Packages
        run: mvn deploy -f ${{ env.STARTER }}/pom.xml --settings .github/maven-settings.xml