name: 'User Service CI'

on:
  push:
    branches: [ 'master' ]
    paths: [ 'user-service/**' ]
env:
  SERVICE: user-service
jobs:
  test:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: tests
        run: mvn -B verify -f ${{env.SERVICE}}

  build-and-push:
    runs-on: ubuntu-22.04
    steps:
      - name: checkout code
        uses: actions/checkout@v3
      - name: login to docker hub
        uses: docker/login-action@v1
        with:
          username: ${{secrets.DOCKER_USERNAME}}
          password: ${{secrets.DOCKER_PASSWORD}}
      - name: build and push docker image
        uses: docker/build-push-action@v2
        with:
          context: ./PATH
          dockerfile: Dockerfile
          push: true
          tags: ${{secrets.DOCKER_USERNAME}}/${{env.SERVICE}}:latest